version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-games-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gamespass
      MYSQL_DATABASE: games_db
    volumes:
      - mysql_games_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 10

  live-games-server:
    image: walaahij/live-games-server:BUILD_ID_PLACEHOLDER
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: gamespass
      DB_NAME: games_db
    ports:
      - "8777:8777"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8777"]
      interval: 10s
      timeout: 5s
      retries: 5

  guess-game:
    image: walaahij/guessgame-image:BUILD_ID_PLACEHOLDER
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: gamespass
      DB_NAME: games_db
    ports:
      - "8778:8778"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8778"]
      interval: 10s
      timeout: 5s
      retries: 5

  memory-game:
    image: walaahij/memorygame-image:BUILD_ID_PLACEHOLDER
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: gamespass
      DB_NAME: games_db
    ports:
      - "8779:8779"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8779"]
      interval: 10s
      timeout: 5s
      retries: 5

  currencyroulette-game:
    image: walaahij/currencyroulettegame-image:BUILD_ID_PLACEHOLDER
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: gamespass
      DB_NAME: games_db
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_games_data:
