version: '3.8'
services:
  app:
    build: .
    ports:
      - "8777:8777"
    volumes:
      - ./scores_file.txt:/app/Scores.txt                  # mounts files or directories from your host into the container.
    networks:
      - test-network

  selenium-hub:
    image: selenium/hub:4.1.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - test-network

  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - test-network

networks:
  test-network: